require 'pathname'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"

prepare_react_native_project!

target 'PDFViewer-macOS' do
  platform :macos, '14.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)

    jsinspector_header_paths = [
      '"$(PODS_ROOT)/../../node_modules/react-native-macos/ReactCommon/jsinspector-modern"',
      '"$(PODS_ROOT)/Headers/Public/React-jsinspector/jsinspector-modern"',
      '"$(PODS_ROOT)/Headers/Private/React-jsinspector/jsinspector-modern"',
    ]

    installer.pods_project.targets.each do |target|
      next unless target.name.start_with?('React-')

      extra_header_paths = ['"$(PODS_TARGET_SRCROOT)"']
      if target.name.start_with?('React-jsinspector')
        extra_header_paths += jsinspector_header_paths
      end

      target.build_configurations.each do |config|
        paths = config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)']
        paths = paths.split(' ') if paths.is_a?(String)
        config.build_settings['HEADER_SEARCH_PATHS'] = (paths + extra_header_paths).uniq
      end
    end
  end
end
